default: &default
  adapter: postgresql
  username: cesar
  password: kele060990
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: punto_de_venta_development

test:
  <<: *default
  database: punto_de_venta_test

production:
  <<: *default
  database: punto_de_venta_production